RULES = [
    {
        "id": "OCI-COMPUTE-001",
        "resource_type": "Compute",
        "name": "Instance with Public IP",
        "severity": "Medium",
        "description": "Compute instance has a public IP address and is exposed to the internet.",
        "recommendation": "Remove public IP attachment and use a bastion or private endpoint.",
        "check": lambda config: config.get("has_public_ip", False),
    },
    {
        "id": "OCI-NET-001",
        "resource_type": "Subnet",
        "name": "Public Subnet Enabled",
        "severity": "Low",
        "description": "Subnet is public and allows public IP addresses on VNICs.",
        "recommendation": "Make the subnet private and route traffic through a NAT Gateway.",
        "check": lambda config: config.get("is_public", False),
    },
    {
        "id": "OCI-NET-002",
        "resource_type": "SecurityList",
        "name": "Public SSH Access Allowed",
        "severity": "High",
        "description": "Security List allows incoming SSH traffic (port 22) from all source IPs (0.0.0.0/0).",
        "recommendation": "Restrict source CIDR blocks to trusted IP addresses.",
        "check": lambda config: config.get("public_ssh", False),
    },
    {
        "id": "OCI-NET-003",
        "resource_type": "SecurityList",
        "name": "Public RDP Access Allowed",
        "severity": "High",
        "description": "Security List allows incoming RDP traffic (port 3389) from all source IPs (0.0.0.0/0).",
        "recommendation": "Restrict source CIDR blocks to trusted IP addresses.",
        "check": lambda config: config.get("public_rdp", False),
    },
    {
        "id": "OCI-STORAGE-001",
        "resource_type": "ObjectStorage",
        "name": "Public Object Storage Bucket",
        "severity": "High",
        "description": "Object Storage bucket allows public access.",
        "recommendation": "Configure the bucket's public access type to 'NoPublicAccess'.",
        "check": lambda config: config.get("is_public", False),
    },
    {
        "id": "OCI-STORAGE-002",
        "resource_type": "ObjectStorage",
        "name": "Bucket Customer-Managed Key Encryption Disabled",
        "severity": "Medium",
        "description": "Object Storage bucket is not encrypted using a Customer-Managed Key (KMS).",
        "recommendation": "Enable KMS Customer-Managed Key encryption on the bucket.",
        "check": lambda config: not config.get("encrypted_with_cmk", False),
    },
    {
        "id": "OCI-IAM-001",
        "resource_type": "IAM_Users",
        "name": "MFA Not Enabled for User",
        "severity": "High",
        "description": "IAM User does not have Multi-Factor Authentication (MFA) enabled.",
        "recommendation": "Enable MFA for the user under identity credentials.",
        "check": lambda config: not config.get("is_mfa_activated", False),
    },
    {
        "id": "OCI-IAM-002",
        "resource_type": "IAM_Users",
        "name": "Too Many Active API Keys",
        "severity": "Low",
        "description": "IAM User has more than 1 active API key.",
        "recommendation": "Delete or rotate unused API keys to reduce credential leak risks.",
        "check": lambda config: config.get("api_key_count", 0) > 1,
    },
    {
        "id": "OCI-IAM-003",
        "resource_type": "IAM_Policies",
        "name": "Overly Permissive Policy",
        "severity": "High",
        "description": "IAM Policy contains statements that allow managing all resources.",
        "recommendation": "Restrict policy statements to follow the principle of least privilege.",
        "check": lambda config: config.get("has_broad_permissions", False),
    }
]
